name: apply
on:
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read
  
jobs:
  apply:
    uses: ./.github/workflows/tf-base.yml
    with:
      mode: apply
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
