name: apply
on:
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    uses: ./.github/workflows/tf-base.yml
    with:
      mode: apply
      tf_workdir: envs/dev
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      MA_GITHUB_TOKEN: ${{ secrets.MA_GITHUB_TOKEN }}
      MA_ADMIN_TOKEN:  ${{ secrets.MA_ADMIN_TOKEN }}
