name: destroy
on:
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    uses: ./.github/workflows/tf-base.yml
    with:
      mode: destroy
      tf_workdir: envs/dev
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}

