name: plan
on:
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read
  
jobs:
  plan:
    uses: ./.github/workflows/tf-base.yml
    with:
      mode: plan
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
